site_name: KOReader compendium
site_description: KOReader knowledgebase
site_url: https://dmpop.github.io/koreader-compendium/
site_author: Dmitri Popov
repo_url: https://github.com/dmpop/koreader-compendium/
edit_uri: blob/main/docs/
copyright: Creative Commons CC0
theme:
  name: material
  font:
    text: Lato
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search